src/App.jsx
src/components/Button/RegisterBtn.Styled.js
src/components/Button/RegisterBtn.jsx
src/components/common/Input.Styled.js
src/components/common/Input.jsx
src/components/signup/SignUp.Styled.js
src/components/signup/SignUp.jsx
src/router.jsx

10 feat 회원가입 페이지 구현

---

src/components/FavoriteCafeList/FavoriteCafeList.jsx
src/components/FavoriteCafeList/styled.js
src/pages/FavoriteCafe.jsx
src/router.jsx

#45 
1. 공통 컴포넌트 불러와서 즐겨찾는 카페 리스트 완성
1. 뒤로가기 연결
2. 스크롤 기능 추가

feat/#45/즐겨찾는 카페 페이지 구현 완료

---

src/components/MyPage/ProfileContent.jsx
src/components/MyPage/ProfileInfo.jsx
src/components/MyPage/StateBar.jsx
src/components/MyPage/styled.js
src/pages/MyPage.jsx

#48 
1. 텀블러 적립 횟수에 따른 레벨 상태 바 연결
2. 레벨에 따른 프로필 이미지 변경 구현
3. 데이터 props로 연결
1. 각각 컴포넌트 클릭 시 페이지 연결
2. 취향 데이터 받아오기

chore/#48/상태바 연결 및 마이페이지 데이터 props 연결

---

src/components/Coupon/MyCoupon.jsx
src/components/FavoriteCafeList/FavoriteCafeList.jsx

#68 
1. 즐겨찾는 카페 페이지 연동
1. 카페리스트카드 레이아웃 수정 (카페 이름 길어질때 처리)

api/#68/즐겨찾는 카페 페이지 연동 완료 및 목데이터 삭제

---

src/components/Map/KakaoMap.jsx
src/components/Map/Map.jsx
src/components/Map/MapCafeCard.jsx
src/router.jsx

#64 
- 지도 - 카페 찾기에서 새싹 모양(카페)을 클릭하면 카페 카드가 하단바 위에 나타나도록 하기
- 카페 카드 컴포넌트로 만들기
🌟 카페 카드는 `카페명` `카페 이미지` `즐겨찾기 여부` `위치` `운영시간` 포함
- 새싹 클릭 시 카드 컴포넌트 나타나도록 하기

64 feat 새싹 클릭 시 나타나는 카페 카드 구현

---

src/components/CafeInfo/CafeDetail.jsx
src/components/getStamp/GetStamp.Styled.js
src/components/getStamp/GetStamp.jsx
src/components/getStamp/StampAccess.jsx

#99 
1. 직원 확인코드 연동 - 인증 코드 일치하면, 스탬프 적립 1 (백엔드 처리), 스탬프 적립 페이지로 이동
2. 스탬프 적립 페이지 경로 수정 (홈화면, 쿠폰)
스탬프 적립 페이지가 직원 확인 코드 위 붙으면서 레이아웃에 문제가 생기는데,, 수정이 더 필요할 것 같습니다!

Api/#99/직원 확인코드 스탬프 적립 연동

---

src/components/Map/KakaoMap.jsx
src/components/Map/Map.jsx
src/components/Map/SearchBox.jsx
src/components/getStamp/QrScan.jsx

#101 
- 지도 페이지가 처음 실행될 때 디폴트 위치를 현재 위치로 설정
- 지도 키워드 검색 연동

Api/#101/지도 검색 연동 및 레이아웃 조정

---

src/components/CafeList/CafeList.Styled.js
src/components/Coupon/styled.js
src/components/FavoriteCafeList/styled.js
src/components/Home/styled.js
src/components/Preference/styled.js
src/components/common/Footer.Styled.js
src/components/common/Header.Styled.js
src/index.css
src/pages/HomePage.jsx
src/pages/MyPage.jsx

Style/#104/모바일 뷰 레이아웃 조정

---

src/components/CafeInfo/CafeDetail.jsx
src/components/CafeList/CafeList.jsx
src/components/Coupon/CouponChange.jsx
src/components/Coupon/MyCoupon.jsx
src/components/FavoriteCafeList/FavoriteCafeList.jsx
src/components/Map/KakaoMap.jsx
src/components/Map/MapCafeCard.jsx
src/components/Preference/ChoosePreference.jsx
src/components/getStamp/StampAccess.jsx
src/components/login/Login.jsx
src/components/signup/SignUp.jsx
src/pages/CouponDetailPage.jsx
src/pages/MyPage.jsx
src/pages/ProfileShare.jsx

Chore/#112/환경변수로 API 주소 관리 수정 완료

---

src/components/CafeInfo/CafeDetail.jsx
src/components/Home/CafeCarousel.jsx
src/components/common/CafeListCard.jsx
src/components/getStamp/StampAccess.jsx
src/router.jsx

#116 
1. 스탬프 적립하기 페이지 및 카페 상세정보 페이지 params 이용하여 라우팅 주소 변경

fix/#116/스탬프 적립 페이지 params 사용

---

src/components/Map/Map.jsx

118 feat 지도 검색 기능 구현 및 레이아웃 조정

---

src/components/getStamp/QrVer2.jsx

feat/#123/큐알코드 기능 구현

---

src/components/getStamp/QrVer2.jsx

123 feat 큐알 코드 스캔 기능 및 스탬프 적립 api 연동

---

src/components/getStamp/QrScan.jsx

#129 
- 지도 카페 카드에서 부모 컴포넌트 눌러도 이동하지 않고, 즐겨찾기 버튼 잘 눌리도록 수정

129 chore 즐겨찾기 이벤트 버블링 막기

---

src/components/getStamp/StampAccess.Styled.js

#132 
1. 스탬프 직원 확인 코드 페이지 스타일 조정 (이미지 및 텍스트 밑으로 내려 여백 확보)

style/#132/StampAccess 컴포넌트 스타일 수정

---

src/components/getStamp/QrScan.jsx

Feat/#133/큐알코드 카페별 url 이동

---

src/components/getStamp/QrScan.jsx

133 feat 큐알코드 카페별 url 이동

---

src/components/getStamp/QrScan.jsx

143 chore 내 현재 위치 좌표 넘겨주기

---

src/components/Home/CafeCarousel.jsx
src/components/Home/styled.js

#148 
1. 메인화면의 카페 캐러셀 로딩중 텍스트 프리텐다드 폰트 설정

Style/#148/카페 캐러셀 로딩중 텍스트 폰트 설정

---

src/pages/StampAccess.jsx

Chore/#153/주석 처리 코드 지우기

---

src/components/Coupon/CouponChange.jsx
src/components/Coupon/styled.js
src/components/Home/styled.js
src/components/MyPage/styled.js
src/components/common/NoticeModal.Styled.js
src/components/common/PwdInputField.Styled.js
src/components/getStamp/GetStamp.Styled.js
src/components/getStamp/StampAccess.Styled.js
src/components/onboarding/Splash.Styled.js
src/pages/MyPage.jsx
src/pages/OnBoarding.jsx

#158 
온보딩 페이지, 홈화면, 마이페이지 너비 조정 완료

Design/#158/온보딩 및 홈화면, 마이페이지 너비 조정

---

src/components/CafeInfo/CafeInfo.Styled.js
src/components/CafeInfo/CafeInfoBox.jsx
src/components/CafeInfo/MenuBox.jsx
src/components/Map/KakaoMap.jsx
src/components/Map/Map.Styled.js
src/components/Map/MapBtn.jsx
src/components/Map/MapCafeCard.jsx
src/components/Map/SearchBox.jsx

#161 
1️⃣ 지도 스타일 컴포넌트 파일 분리
2️⃣ 카페 정보 스타일 컴포넌트 파일 분리

161 chore 스타일 컴포넌트 파일 분리

---

src/apis/api.js

refreshApi 요청 방식 변경

---

src/components/MyPage/ProfileInfo.jsx
src/components/MyPage/styled.js

#166 
현재 텀블러인 서비스에는 로그아웃 로직 존재 X
-> 사용자가 직접 브라우저 쿠키를 삭제하지 않는 이상 세션이 유지되는 문제가 있음 🤔
Refresh Token을 쿠키로 관리하는 로그인 방식 적용하면서, 보안을 위해 서버와 쿠키를 모두 안전하게 초기화할 수 있도록 로그아웃 기능 구현
```
1. 백엔드 로그아웃 API 연동 (Refresh Token 무효화)
2. UI 수정사항 반영 (로그아웃 버튼)
3. 로그아웃 테스트
```

Feat/#166/로그아웃 기능 구현

---

src/pages/QrScan.jsx

#174 
```
카페의 QR코드를 인식하는 페이지 로직 중 이해하기 어려운 부분이 있어 주석을 추가하였음
✅ QR 인식 흐름 분석 후 주석 추가 (로직 이해를 돕기 위함)
✅ 불필요한 코드 리팩토링
```

Chore/#174/큐알코드 페이지 주석 추가

---

src/components/CafeInfo/CafeInfo.Styled.js
src/components/FavoriteCafeList/styled.js
src/components/Map/Map.Styled.js
src/components/getStamp/GetStamp.Styled.js

#178 
1. 스탬프 적립 완료 쿠폰 너비 수정
2. 지도 카페 카드 너비 수정
3. 카페 상세정보 메뉴 정보 간격 수정
4. 즐겨찾는 카페 목록 레이아웃 수정

Design/#178/컴포넌트 추가 너비 조정
